# Generated by Django 3.1.4 on 2021-01-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='year_founded',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
